services:
    cron.executor:
        class: SymfonyContrib\Bundle\CronBundle\CronExecutor
        arguments:
            - "@logger"
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - name: monolog.logger
              channel: cron

    cron.twig.extension:
        class: SymfonyContrib\Bundle\CronBundle\Twig\CronExtension
        tags:
            - name: twig.extension
